#For building: sudo docker build -t redteam/weaponi:latest -f Dockerfile-weaponization .
#For execute: sudo docker run --name redteam_weaponi --rm -i -t redteam/weaponi bash
FROM debian:latest AS base
	LABEL author="Adastra"
	LABEL description="Simple Red Team image."
	ENV WORKDIR_ENV=/directorio
	WORKDIR ${WORKDIR_ENV}
	SHELL ["/bin/bash", "-c"]

  RUN apt-get update && apt-get -y install apt-utils net-tools netcat \
                        python3 python3-dev python3-pip unzip wget curl \
                        git gcc libc-dev libxslt-dev libevent-dev libssl-dev \
                        zlib1g zlib1g-dev firefox-esr xfce4-terminal autoconf automake \
                        libtool apt-utils openssh-server openssl build-essential \
                        libpcap-dev libpq-dev libsqlite3-dev libsqlite3-dev libsqlite3-0


	#Clone repositories from recon-ng, photon, theHarvester and MaliciousMacroGenerator
	RUN ${WORKDIR} && git clone  https://github.com/WyAtu/CVE-2018-20250\
                    && git clone  https://github.com/bhdresh/CVE-2017-8759\
                    && git clone  https://github.com/rxwx/CVE-2017-8570\
                    && git clone https://github.com/bhdresh/CVE-2017-0199\
                    && git clone https://github.com/nccgroup/demiguise\
                    && git clone https://github.com/Mr-Un1k0d3r/MaliciousMacroGenerator\
                    && git clone https://github.com/0xdeadbeefJERKY/Office-DDE-Payloads && cd Office-DDE-Payloads && pip3 install -r requirements.txt\
                    && ${WORKDIR} && git clone https://github.com/Mr-Un1k0d3r/DKMC && cd DKMC && mkdir output\
                    && ${WORKDIR} && git clone https://github.com/Arno0x/EmbedInHTML \
                    && mkdir macro_pack && cd macro_pack && wget https://github.com/sevagas/macro_pack/releases/tag/v1.7/macro_pack.exe
