#For building: sudo docker build -t redteam/anon:latest -f Dockerfile-anon .
#For execute: sudo docker run --name redteam_anon --rm -v "$(pwd)"/anonServices-vol:/anonServices -v "$(pwd)"/torService:/var/lib/tor/ -i -t redteam/anon bash


FROM debian:latest AS base
	LABEL author="daffi1238"
	LABEL description="Anon Red team image."
	ENV WORKDIR_ENV=/anonServices
	WORKDIR ${WORKDIR_ENV}
	SHELL ["/bin/bash", "-c"]

	RUN apt-get update && apt-get -y install apt-utils net-tools netcat \
python3 python3-dev python3-pip unzip wget curl sudo \
git gcc libc-dev libxslt-dev libevent-dev libssl-dev \
zlib1g zlib1g-dev firefox-esr xfce4-terminal autoconf automake \
libtool apt-utils openssh-server openssl build-essential \
libpcap-dev libpq-dev libsqlite3-dev libsqlite3-dev libsqlite3-0 \
nano tor python \
#Para crear un directorio para una web en la red onion
&& mkdir /webdir && chown debian-tor:debian-tor /webdir && chmod 700 /webdir \
