#For building: sudo docker build -t redteam/anon:latest -f Dockerfile-anon .
#For execute: sudo docker run --name redteam_anon --rm -i -t redteam/anon bash
FROM debian:latest AS base
	LABEL author="Adastra"
	LABEL description="Simple Red Team image."
	ENV WORKDIR_ENV=/directorio
	WORKDIR ${WORKDIR_ENV}
	SHELL ["/bin/bash", "-c"]

	RUN apt-get update && apt-get -y install apt-utils net-tools netcat \
                        python3 python3-dev python3-pip unzip wget curl \
                        git gcc libc-dev libxslt-dev libevent-dev libssl-dev \
                        zlib1g zlib1g-dev firefox-esr xfce4-terminal autoconf automake \
                        libtool apt-utils openssh-server openssl build-essential \
                        libpcap-dev libpq-dev libsqlite3-dev libsqlite3-dev libsqlite3-0


#Install tor from source
	RUN ${WORKDIR} \
                  && wget https://dist.torproject.org/tor-0.4.5.6.tar.gz\
                  && tar -xvf tor-0.4.5.6.tar.gz \
                  && rm -rf tor-0.4.5.6.tar.gz \
                  && mv tor-0.4.5.6 tor-latest \
                  && cd tor-latest && ./configure && make
