#For building: docker build -t adastra/redteamdocker:latest -f Dockerfile-redteam .
FROM debian:latest AS base
	LABEL author="Adastra"
	LABEL description="Simple Red Team image."
	ENV WORKDIR_ENV=/redteam
	WORKDIR ${WORKDIR_ENV}
	SHELL ["/bin/bash", "-c"]

	RUN apt-get update && apt-get -y install apt-utils net-tools netcat python3 python3-dev python3-pip unzip wget curl git gcc libc-dev libxslt-dev libevent-dev libssl-dev zlib1g zlib1g-dev firefox-esr xfce4-terminal autoconf automake libtool apt-utils openssh-server openssl build-essential libpcap-dev libpq-dev libsqlite3-dev libsqlite3-dev libsqlite3-0

	#Clone repositories from recon-ng, photon, theHarvester and MaliciousMacroGenerator
	RUN cd ${WORKDIR} && git clone https://github.com/lanmaster53/recon-ng.git
	RUN cd ${WORKDIR} && git clone https://github.com/s0md3v/Photon.git
	RUN cd ${WORKDIR} && git clone https://github.com/laramies/theHarvester.git
	RUN cd ${WORKDIR} && git clone https://github.com/Mr-Un1k0d3r/MaliciousMacroGenerator.git

	#Install tor from source
	RUN cd ${WORKDIR} && wget https://dist.torproject.org/tor-0.4.5.6.tar.gz && tar -xvf tor-0.4.5.6.tar.gz && rm -rf tor-0.4.5.6.tar.gz && mv tor-0.4.5.6 tor-latest
