#For building: sudo docker build -t redteam/recon:latest -f Dockerfile-recon .
#For execute: sudo docker run --name redteam_recon --rm -i -t redteam/recon bash

FROM debian:latest AS base
	LABEL author="Adastra"
	LABEL description="Simple Red Team image."
	ENV WORKDIR_ENV=/directorio
	WORKDIR ${WORKDIR_ENV}
	SHELL ["/bin/bash", "-c"]

  RUN apt-get update && apt-get -y install apt-utils net-tools netcat \
                        python3 python3-dev python3-pip unzip wget curl \
                        git gcc libc-dev libxslt-dev libevent-dev libssl-dev \
                        zlib1g zlib1g-dev firefox-esr xfce4-terminal autoconf automake \
                        libtool apt-utils openssh-server openssl build-essential \
                        libpcap-dev libpq-dev libsqlite3-dev libsqlite3-dev libsqlite3-0


	#Clone repositories from recon-ng, photon, theHarvester and MaliciousMacroGenerator
	RUN ${WORKDIR} && git clone https://github.com/lanmaster53/recon-ng.git \
                    && git clone https://github.com/s0md3v/Photon \
                    && git clone https://github.com/laramies/theHarvester \
                    && git clone https://github.com/Mr-Un1k0d3r/MaliciousMacroGenerator
